use rfehr2;

CREATE TABLE IF NOT EXISTS USER_T (
USER_ID INT AUTO_INCREMENT NOT NULL,
USER_F_NAME VARCHAR(20) NOT NULL,
USER_L_NAME VARCHAR(20) NOT NULL,
USER_EMAIL VARCHAR(100) NOT NULL,
USER_PASSWORD VARCHAR(20) NOT NULL,
PRIMARY KEY (USER_ID));

